apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name}}
spec:
  type: {{ .Values.service.type }}
  ports:
  - nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    targetPort: 8080
  selector:
    run: {{ .Values.Name}}


