namespace: 
  name: pandas 
  deploy: true
env: dev
services:
  expose_node_port: true
docker:
  #registry: 10.4.47.129:5000
  namespace: cloustone 
  image_prefix: pandas-
  pullPolicy: Always
public:
  namespace: kube-public
  ingress:
    deploy: false
  prometheus: 
    address: prometheus.kube-public:9090
  etcd:
    address: etcd.kube-public:2379
    username: test
    password: test
    prefix: test
  redis:
    address: redis.kube-public:6379
    port: 6379
  rabbitmq:
    address: rabbitmq.kube-public
    username: pandas 
    password: pandas 
    port:
      epmd: 4369
      amqp: 5672
      stats: 15672
      dist: 25672

apimachinery:
  deploy: true
  version: latest
  port: 30001
  cpus: 100m
  memory: 256Mi
dmms:
  deploy: true
  version: latest
  port: 0 
  cpus: 100m
  memory: 256Mi
pms:
  deploy: true
  version: latest
  port: 0 
  cpus: 100m
  memory: 256Mi
headmast:
  deploy: true
  version: latest
  port: 0 
  cpus: 100m
  memory: 256Mi
rulechain:
  deploy: true
  version: latest
  port: 0
  cpus: 100m
  memory: 64Mi
lbs:
  deploy: true
  version: latest
  port: 0
  cpus: 100m
  memory: 64Mi
  baidu:
    service_id: pandas
    ak: xxxxxxxxxx

dashboard:
  deploy: false
  version: latest
  port: 30880
  cpus: 100m
  memory: 64Mi

nats:
  deploy: true
  url: nats:4222 
  port: 4222
  targetport: 4222

jaeger:
  deploy: true
  port:
    pod: 6831
    frontend: 16686
    collect: 14268
    configs: 5778
  url: jaeger:6831

redis:
  deploy: true
  port: 6379
  things_url: things-redis:6379
  es_url: es-redis:6379

authn_db:
  deploy: true
  port: 5432
  dbname: authn
  username: mainflux
  password: mainflux

authn:
  deploy: true
  url: authn:8181
  port: 8181
  targetport: 8181
  db:
    name: authn
    host: authn-db
    user: mainflux
    pass: mainflux
  log_level: debug 
  secret: secret

things:
  deploy: true 
  url: things:8183
  port: 8183
  targetport: 8183
  db:
    name: things
    host: things-db
    user: mainflux
    pass: mainflux
  log_level: debug  
  secret: secret

things_db:
  deploy: true
  port: 5432
  dbname: things
  username: mainflux
  password: mainflux

users_db:
  deploy: true
  port: 5432
  dbname: users
  username: mainflux
  password: mainflux

users:
  deploy: true
  port: 8180
  targetport: 8180
  db:
    name: users
    host: users-db
    user: mainflux
    pass: mainflux
  log_level: debug 
  secret: secret
  email:
    driver: smtp
    from: 
      address: from@example.com
      name: Example
    host: smtp.mailtrap.io
    pass: 2b0d302e775b1e
    name: 18bf7f70705139
    temp: email.tmpl
  token: /reset-request

mqtt_adapter:
  deploy: true 
  port: 
    ws: 8880
    ws_broker: 8881
    port: 1883
    target: 1883
    broker: 1883
  log_level: debug
  target_host: vernemq

coap_adapter:
  deploy: true
  log_level: debug 
  port: 5683
  targetport: 5683

ws_adapter:
  deploy: true
  log_level: debug 
  port: 8186
  targetport: 8186
  
vernemq:
  deploy: true
  log_level: debug 
  port: 
    port1: 18831
    port2: 8881
    port3: 8888
  anonymous: "'on'"
  log_level: info