namespace: 
  name: namespace 
  deploy: false
env: dev
services:
  expose_node_port: true
docker:
  registry: 10.4.47.129:5000
  namespace: cloustone 
  image_prefix: pandas-
  pullPolicy: Always
public:
  namespace: kube-public
  ingress:
    deploy: false
  prometheus: 
    address: prometheus.kube-public:9090
  etcd:
    address: etcd.kube-public:2379
    username: test
    password: test
    prefix: test
  redis:
    address: redis.kube-public:6379
    port: 6379
  rabbitmq:
    address: rabbitmq.kube-public
    username: pandas 
    password: pandas 
    port:
      epmd: 4369
      amqp: 5672
      stats: 15672
      dist: 25672

apimachinery:
  deploy: false
  version: latest
  port: 30001
  cpus: 100m
  memory: 256Mi
dmms:
  deploy: false
  version: latest
  port: 0 
  cpus: 100m
  memory: 256Mi
pms:
  deploy: false
  version: latest
  port: 0 
  cpus: 100m
  memory: 256Mi
headmast:
  deploy: false
  version: latest
  port: 0 
  cpus: 100m
  memory: 256Mi
rulechain:
  deploy: false
  version: latest
  port: 0
  cpus: 100m
  memory: 64Mi
lbs:
  deploy: true
  version: latest
  port: 0
  cpus: 100m
  memory: 64Mi
  baidu:
    service_id: pandas
    ak: xxxxxxxxxx
shiro:
  deploy: false
  version: latest
  port: 0
  cpus: 100m
  memory: 256Mi
dashboard:
  deploy: false
  version: latest
  port: 30880
  cpus: 100m
  memory: 64Mi
