namespace: 
  name: mainflux
  deploy: true
env: dev
services:
  expose_node_port: true
docker:
  namespace: mainflux 
  image_prefix: mainflux-
  pullPolicy: Always
dockerregistry:
  deploy: true
  version: latest
  port: 0
  replicas: 1
  cpus: 100m
  memory: 64Mi
dockerauth:
  deploy: true
redis:
  deploy: true
  port: 6379
  things_url: things-redis:6379
  es_url: es-redis:6379
things_db:
  deploy: true
  port: 5432
  dbname: things
  username: mainflux
  password: mainflux
authn_db:
  deploy: true
  port: 5432
  dbname: authn
  username: mainflux
  password: mainflux
users_db:
  deploy: true
  port: 5432
  dbname: users
  username: mainflux
  password: mainflux
jaeger:
  deploy: true
  port:
    pod: 6831
    frontend: 16686
    collect: 14268
    configs: 5778
  url: jaeger:6831

mqtt_adapter:
  deploy: true 
  port: 
    ws: 8880
    ws_broker: 8881
    port: 1883
    target: 1883
    broker: 1883
  log_level: debug
  target_host: vernemq
nats:
  deploy: true
  url: nats:4222 
  port: 4222
  targetport: 4222
http_adapter:
  deploy: true 
  log_level: debug 
  port: 8185
  targetport: 8185

things:
  deploy: true 
  url: things:8183
  port: 8183
  targetport: 8183
  db:
    name: things
    host: things-db
    user: mainflux
    pass: mainflux
  log_level: debug  
  secret: secret

authn:
  deploy: true
  url: authn:8181
  port: 8181
  targetport: 8181
  db:
    name: authn
    host: authn-db
    user: mainflux
    pass: mainflux
  log_level: debug 
  secret: secret
users:
  deploy: true
  port: 8180
  targetport: 8180
  db:
    name: users
    host: users-db
    user: mainflux
    pass: mainflux
  log_level: debug 
  secret: secret
  email:
    driver: smtp
    from: 
      address: from@example.com
      name: Example
    host: smtp.mailtrap.io
    pass: 2b0d302e775b1e
    name: 18bf7f70705139
    temp: email.tmpl
  token: /reset-request
coap_adapter:
  deploy: true
  log_level: debug 
  port: 5683
  targetport: 5683
ws_adapter:
  deploy: true
  log_level: debug 
  port: 8186
  targetport: 8186
vernemq:
  deploy: true
  log_level: debug 
  port: 
    port1: 18831
    port2: 8881
    port3: 8888
  anonymous: "'on'"
  log_level: info

nginx:
  port: 80

