{{ if .Values.apimachinery.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandas-apimachinery
  namespace: {{.Values.namespace.name}}
  labels:
    service: pandas-apimachinery
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pandas-apimachinery
  template:
    metadata:
      labels:
        service: pandas-apimachinery
    spec:
      containers:
      - name: pandas-apimachinery
        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}/{{.Values.docker.image_prefix}}apimachinery:{{.Values.apimachinery.version}}
{{ if .Values.docker.pullPolicy }}
        imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
        ports:
        - containerPort: 8080
        command: ["/bin/sh", "-c"]
        args: ["PANDAS_PORT=8080 /main"]
        env:
        - name: PANDAS_POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: PANDAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: {{.Values.apimachinery.cpus}}
            memory: {{.Values.apimachinery.memory}}

---

apiVersion: v1
kind: Service
metadata:
  name: pandas-apimachinery
  namespace: {{.Values.namespace.name}}
  labels:
    service: pandas-apimachinery
spec:
  type: NodePort
  ports:
  - name: pandas-apiservice
    port: 80
    targetPort: 8080
    nodePort: {{.Values.apimachinery.port}}
  selector:
    service: pandas-apimachinery
{{ end }}
