{{ if .Values.lbs.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: lbs-secrets
  namespace: {{.Values.namespace.name}}
type: Opaque
data:
  PANDAS_BAIDU_SERVICE_ID: {{.Values.lbs.baidu.service_id|b64enc}}
  PANDAS_BAIDU_AK: {{.Values.lbs.baidu.ak|b64enc}}
{{ end }}
