{{ if .Values.lbs.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: lbs-secrets
  namespace: {{.Values.namespace.name}}
type: Opaque
data:
  PANDAS_ETCD_ADDRESS: {{printf "http://%s" .Values.public.etcd.address|b64enc}}
  PANDAS_ETCD_USERNAME: {{.Values.public.etcd.username|b64enc}}
  PANDAS_ETCD_PASSWORD: {{.Values.public.etcd.password|b64enc}}
  PANDAS_ETCD_PREFIX: {{.Values.public.etcd.prefix|b64enc}}
  PANDAS_ETCD_CERT: {{.Values.public.etcd.cert}} #assumed to be already encoded
  PANDAS_BAIDU_SERVICE_ID: {{.Values.lbs.baidu.service_id|b64enc}}
  PANDAS_BAIDU_AK: {{.Values.lbs.baidu.ak|b64enc}}
  PANDAS_MESSAGE_ADDRESS: {{.Values.public.rabbitmq.address|b64enc}}
  PANDAS_MESSAGE_USERNAME: {{.Values.public.rabbitmq.username|b64enc}}
  PANDAS_MESSAGE_PASSWORD: {{.Values.public.rabbitmq.password|b64enc}}
{{ end }}
