apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  namespace: {{.Values.namespace.name}}
  labels:
    service: pandas-mqtt-broker-volume
  name: pandas-mqtt-broker-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
