{{ if .Values.pms.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.docker.image_prefix}}pms
  namespace: {{.Values.namespace.name}}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.docker.image_prefix}}pms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{.Values.docker.image_prefix}}pms
    namespace: {{.Values.namespace.name}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.docker.image_prefix}}pms
  namespace: {{.Values.namespace.name}}
  labels:
    service: {{.Values.docker.image_prefix}}pms
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{.Values.docker.image_prefix}}pms
  template:
    metadata:
      labels:
        service: {{.Values.docker.image_prefix}}pms
    spec:
      serviceAccount: {{.Values.docker.image_prefix}}pms
      serviceAccountName: {{.Values.docker.image_prefix}}pms
      containers:
      - name: {{.Values.docker.image_prefix}}pms
        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}/{{.Values.docker.image_prefix}}pms:{{.Values.pms.version}}
{{ if .Values.docker.pullPolicy }}
        imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
        ports:
        - containerPort:  {{.Values.pms.port }}
        env:
        - name: PANDAS_REDIS_ADDRESS
          value: {{ .Values.public.redis.address }}
        - name: PD_PMS_HTTP_PORT
          value: "8194"
        - name: PD_NATS_URL
          value: {{.Values.nats.url}}
        - name: PD_JAEGER_URL
          value: {{.Values.jaeger.url }}
        - name: PD_PMS_DB
          value: {{.Values.pms.db.name }}
        - name: PD_PMS_DB_HOST
          value: {{.Values.pms.db.host }}
        - name: PD_PMS_DB_PASS
          value: {{.Values.pms.db.pass }}
        - name: PD_PMS_DB_PORT
          value: "5432"
        - name: PD_PMS_DB_USER
          value: {{.Values.pms.db.user }}
        - name: PD_AUTH_URL
          value: {{.Values.authn.url }}
        - name: PD_PMS_SECRET
          value: {{.Values.pms.secret }}
        - name: PD_PMS_CACHE_URL
          value: {{.Values.redis.pms_url }}
        - name: PD_PMS_ES_URL
          value: {{.Values.redis.es_url }}
        resources:
          limits:
            cpu: {{.Values.pms.cpus}}
            memory: {{.Values.pms.memory}}
            
---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.docker.image_prefix}}pms
  namespace: {{.Values.namespace.name}}
  labels:
    service: {{.Values.docker.image_prefix}}pms
spec:
  ports:
  - name: {{.Values.docker.image_prefix}}pms
    port: {{.Values.pms.port }}
    targetPort: {{.Values.pms.targetPort }}
  selector:
    service: {{.Values.docker.image_prefix}}pms
{{ end }}
