{{ if .Values.pms_db.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.docker.image_prefix}}pms-db
  namespace: {{.Values.namespace.name}}
  labels:
    service: {{.Values.docker.image_prefix}}pms-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{.Values.docker.image_prefix}}pms-db
  template:
    metadata:
      labels:
        service: {{.Values.docker.image_prefix}}pms-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{.Values.docker.image_prefix}}pms-db
{{ if .Values.docker.registry }}
          image: {{.Values.docker.registry}}/postgres:10.8-alpine
{{ else }}
          image: postgres:10.8-alpine
{{ end }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: {{.Values.pms_db.port }}
          env:
          - name: POSTGRES_USER
            value: {{.Values.pms_db.username }}
          - name: POSTGRES_PASSWORD
            value: {{.Values.pms_db.password }}
          - name: POSTGRES_DB
            value: {{.Values.pms_db.dbname }}
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: pms-db
  namespace: {{.Values.namespace.name}}
spec:
  ports:
  - port: {{ .Values.pms_db.port }}
    targetPort: {{ .Values.pms_db.port }}
  selector:
    service: {{.Values.docker.image_prefix}}pms-db
{{ end }}
