apiVersion: v1
kind: ReplicationController
metadata:
  name: pms
  labels:
    name: pms
spec:
  replicas: 1
  selector:
    name: pms
  template:
    metadata:
      labels: 
       name: pms
    spec:
      containers:
      - name: pms
        image: 192.168.1.101:5000/pms
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP