{{ if .Values.realms.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.docker.image_prefix}}realms
  namespace: {{.Values.namespace.name}}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.docker.image_prefix}}realms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{.Values.docker.image_prefix}}realms
    namespace: {{.Values.namespace.name}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.docker.image_prefix}}realms
  namespace: {{.Values.namespace.name}}
  labels:
    service: {{.Values.docker.image_prefix}}realms
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{.Values.docker.image_prefix}}realms
  template:
    metadata:
      labels:
        service: {{.Values.docker.image_prefix}}realms
    spec:
      serviceAccount: {{.Values.docker.image_prefix}}realms
      serviceAccountName: {{.Values.docker.image_prefix}}realms
      containers:
      - name: {{.Values.docker.image_prefix}}realms
        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}/{{.Values.docker.image_prefix}}realms:{{.Values.realms.version}}
{{ if .Values.docker.pullPolicy }}
        imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
        ports:
        - containerPort:  {{.Values.realms.port }}
        env:
        - name: PANDAS_REDIS_ADDRESS
          value: {{ .Values.public.redis.address }}
        - name: PD_REALMS_HTTP_PORT
          value: "8195"
        - name: PD_NATS_URL
          value: {{.Values.nats.url}}
        - name: PD_JAEGER_URL
          value: {{.Values.jaeger.url }}
        - name: PD_REALMS_DB
          value: {{.Values.realms.db.name }}
        - name: PD_REALMS_DB_HOST
          value: {{.Values.realms.db.host }}
        - name: PD_REALMS_DB_PASS
          value: {{.Values.realms.db.pass }}
        - name: PD_REALMS_DB_PORT
          value: "5432"
        - name: PD_REALMS_DB_USER
          value: {{.Values.realms.db.user }}
        - name: PD_AUTH_URL
          value: {{.Values.authn.url }}
        - name: PD_REALMS_SECRET
          value: {{.Values.realms.secret }}
        - name: PD_REALMS_CACHE_URL
          value: {{.Values.redis.realms_url }}
        - name: PD_REALMS_ES_URL
          value: {{.Values.redis.es_url }}
        resources:
          limits:
            cpu: {{.Values.realms.cpus}}
            memory: {{.Values.realms.memory}}
            
---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.docker.image_prefix}}realms
  namespace: {{.Values.namespace.name}}
  labels:
    service: {{.Values.docker.image_prefix}}realms
spec:
  ports:
  - name: {{.Values.docker.image_prefix}}realms
    port: {{.Values.realms.port }}
    targetPort: {{.Values.realms.targetPort }}
  selector:
    service: {{.Values.docker.image_prefix}}realms
{{ end }}
