{{ if .Values.rulechain.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.docker.image_prefix}}rulechain
  namespace: {{.Values.namespace.name}}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.docker.image_prefix}}rulechain
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{.Values.docker.image_prefix}}rulechain
    namespace: {{.Values.namespace.name}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandas-rulechain
  namespace: {{.Values.namespace.name}}
  labels:
    service: pandas-rulechain
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pandas-rulechain
  template:
    metadata:
      labels:
        service: pandas-rulechain
    spec:
      serviceAccount: {{.Values.docker.image_prefix}}rulechain
      serviceAccountName: {{.Values.docker.image_prefix}}rulechain
      containers:
      - name: pandas-rulechain
        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}/{{.Values.docker.image_prefix}}rulechain:{{.Values.rulechain.version}}
{{ if .Values.docker.pullPolicy }}
        imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
        ports:
        - containerPort: {{.Values.rulechain.port }}
        command: ["/bin/sh", "-c"]
        args: ["PANDAS_PORT=8189 /main"]
        env:
        - name: PANDAS_POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: PANDAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PANDAS_SERVICE_DISCOVERY_PATH
          value: /pandas
        - name: PANDAS_DEPLOY_MODE
          value: kubernetes
        - name: PANDAS_PRODUCT_REGISTRY
          value: {{.Values.docker.registry}}/{{.Values.docker.namespace}}
        - name: PANDAS_REDIS_ADDRESS
          value: {{ .Values.public.redis.address }}
        - name: PANDAS_MESSAGE_BACKEND
          value: "rabbitmq"
        - name: PANDAS_MESSAGE_ADDRESS
          value: {{ .Values.public.rabbitmq.address }}
        - name: PANDAS_MESSAGE_USERNAME
          value: {{ .Values.public.rabbitmq.username }}
        - name: PANDAS_MESSAGE_PASSWORD
          value: {{ .Values.public.rabbitmq.password }}
   	- name: PD_JAEGER_URL
          value: {{.Values.jaeger.url }}
        - name: PD_TOKEN_RESET_ENDPOINT
          value: {{.Values.rulechain.token }}
        - name: PD_RULECHAIN_DB
          value: {{.Values.rulechain.db.name }}
        - name: PD_RULECHAIN_DB_HOST
          value: {{.Values.rulechain.db.host }}
        - name: PD_RULECHAIN_DB_PASS
          value: {{.Values.rulechain.db.pass }}
        - name: PD_RULECHAIN_DB_PORT
          value: "5432"
        - name: PD_RULECHAIN_DB_USER
          value: {{.Values.rulechain.db.user }}
        - name: PD_RULECHAIN_HTTP_PORT
          value: {{.Values.rulechain.port }}
        - name: PD_RULECHAIN_LOG_LEVEL
          value: {{.Values.rulechain.log_level }}   
        resources:
          limits:
            cpu: {{.Values.rulechain.cpus}}
            memory: {{.Values.rulechain.memory}}
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:4430"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:4430"]
          initialDelaySeconds: 10
            
---

apiVersion: v1
kind: Service
metadata:
  name: pandas-rulechain
  namespace: {{.Values.namespace.name}}
  labels:
    service: pandas-rulechain
spec:
  ports:
  - name: pandas-rulechain
    port: {{.Values.rulechain.port }}
    targetPort: {{.Values.rulechain.targetPort }}
  selector:
    service: pandas-rulechain
{{ end }}
