apiVersion: v1
kind: ReplicationController
metadata:
  name: rulechain
  labels:
    name: rulechain
spec:
  replicas: 3
  selector:
    name: rulechain
  template:
    metadata:
      labels: 
       name: rulechain
    spec:
      containers:
      - name: rulechain
        image: 192.168.1.101:5000/rulechain
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP