apiVersion: v1
kind: Service
metadata:
  name: pandas-rulechain-service
  labels:
    run: pandas-rulechain  
  namespace: default
  resourceVersion: 
  selfLink: 
  uid: 
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pandas-rulechain
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
