apiVersion: v1
kind: Service
metadata:
  labels:
    run: api
  name: api-http
  namespace: default
  resourceVersion: 
  selfLink: 
  uid: 
spec:
  clusterIP: 10.102.214.85
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30721
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
