# Default values for pandas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

Name: pandas-api-gateway

replicas: 1

image: 192.168.1.108:5000/apimachinery:latest

service: 
  type: LoadBalancer
  #nodePort: 30001   #30000-32767
  port: 8080

ingress:
  enabled: false  

